# Generated by Django 5.2.12 on 2026-03-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_leave_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
